/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on Oct 21, 2009, 2:20:04 PM
 */

/**
 *
 * @author levyeh
 */
public class Frame extends javax.swing.JFrame {
	/**
	 * @param args the command line arguments
	 */
	private String[] output;
	private int[] secret;
	private int[][][] history;
	private int round = 0;
	private boolean start = false;

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}



	/** Creates new form Frame */
	public Frame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		startButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		secretArea = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		guessOutput = new javax.swing.JLabel();
		nextButton = new javax.swing.JButton();
		finalOutput = new javax.swing.JLabel();
		baseField = new javax.swing.JComboBox();
		nField = new javax.swing.JComboBox();
		maxField = new javax.swing.JComboBox();
		exitButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(204, 204, 255));

		jPanel1.setBackground(new java.awt.Color(204, 204, 255));

		jLabel1.setFont(new java.awt.Font("Algerian", 0, 30));
		jLabel1.setText("MASTERMIND");

		jLabel2.setText("MAX =");

		jLabel3.setText("N =");

		jLabel4.setText("BASE =");

		startButton.setText("start");
		startButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startButtonActionPerformed(evt);
			}
		});

		secretArea.setBackground(new java.awt.Color(204, 204, 255));
		secretArea.setColumns(20);
		secretArea.setFont(new java.awt.Font("Courier New", 0, 20));
		secretArea.setForeground(new java.awt.Color(153, 0, 51));
		secretArea.setLineWrap(true);
		secretArea.setRows(1);
		secretArea.setAutoscrolls(false);
		jScrollPane1.setViewportView(secretArea);

		jLabel5.setText("the SECRET is");

		guessOutput.setFont(new java.awt.Font("Tahoma", 0, 18));
		guessOutput.setText(" ");

		nextButton.setText("next guess");
		nextButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextButtonActionPerformed(evt);
			}
		});

		finalOutput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		finalOutput.setForeground(new java.awt.Color(255, 0, 0));
		finalOutput.setText(" ");

		baseField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

		nField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
		nField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nFieldActionPerformed(evt);
			}
		});

		maxField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " ", " " }));

		exitButton.setText("exit");
		exitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addComponent(jLabel5)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(finalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(guessOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(34, 34, 34)
						.addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(baseField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(41, 41, 41)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(startButton)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
										.addComponent(jLabel2)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(maxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(133, 133, 133))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(150, 150, 150)
						.addComponent(nextButton)
						.addGap(114, 114, 114)
						.addComponent(exitButton)
						.addContainerGap(121, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(125, 125, 125)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(87, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(jLabel2)
								.addComponent(jLabel4)
								.addComponent(baseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(maxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(startButton)
						.addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
								.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
						.addGap(34, 34, 34)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(exitButton)
								.addComponent(nextButton))
						.addGap(40, 40, 40)
						.addComponent(guessOutput)
						.addGap(35, 35, 35)
						.addComponent(finalOutput)
						.addGap(42, 42, 42))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(15, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

		if (this.start==true)
			return;
		finalOutput.setText("");
		int base = baseField.getSelectedIndex()+2;
		int n = nField.getSelectedIndex()+2;
		int max = maxField.getSelectedIndex()+1;
		if (n>base){
			finalOutput.setText("N cant be greater than BASE !!!");
			return;
		}
		this.start = true;
		Mastermind.BASE = base;
		Mastermind.N = n;
		Mastermind.MAX_ROUND_NUMBER = max;

		this.secret = Mastermind.randomizeSequence();
		//System.out.print("HJERER");
		String stars = "";
		for (int i = 0; i < this.secret.length; i++) {
			stars+= "* ";
		}
		secretArea.setText(stars);


		this.history = Mastermind.play(this.secret);
		this.output = setOutput();

	}//GEN-LAST:event_startButtonActionPerformed

	private String[] setOutput() {
		int j = 0;
		while(j< this.history.length && this.history[j][0]!=null)
			j++;
		String[] ans = new String[j+1] ;
		int i = 0;
		for (; i < this.history.length && this.history[i][0]!=null; i++) {
			ans[i]="";
			ans[i]+="the guess ";
			ans[i]+=arrayToString(this.history[i][0]);
			ans[i]+=" gives (h/f): ";
			ans[i]+=arrayToString(this.history[i][1]);

		}
		int lastRound = i-1;
		if(this.history[lastRound][1][0]==Mastermind.N)
			ans[j] = ("you guessed the secret within "+i+" rounds");
		else
			ans[j] = ("you failed guessing the secret within MAX_ROUND_NUMBER="+ Mastermind.MAX_ROUND_NUMBER + " rounds");
		return ans;

	}



	private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
		if (this.start==false){
			guessOutput.setText("Select Base/N/Max first");
			return;
		}
		if(this.round<this.output.length-1)
			guessOutput.setText(this.output[this.round]);
		if(this.round==this.output.length-1){
			secretArea.setText(arrayToString(this.secret));
			finalOutput.setText(this.output[this.round]);
			Mastermind.printGame(this.secret, this.history);
		}
		this.round++;

	}//GEN-LAST:event_nextButtonActionPerformed

	private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
		// TODO add your handling code here:
		System.exit(ABORT);
	}//GEN-LAST:event_exitButtonActionPerformed

	private void nFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_nFieldActionPerformed




	public static void play() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}


	private String arrayToString(int[] arr){
		String ans = "";
		for (int i = 0; i < arr.length-1; i++) {
			ans += arr[i] + " ";
		}
		ans += arr[arr.length-1];
		return ans;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox baseField;
	private javax.swing.JButton exitButton;
	private javax.swing.JLabel finalOutput;
	private javax.swing.JLabel guessOutput;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox maxField;
	private javax.swing.JComboBox nField;
	private javax.swing.JButton nextButton;
	private javax.swing.JTextArea secretArea;
	private javax.swing.JButton startButton;
	// End of variables declaration//GEN-END:variables

}
